INSERT INTO COUNTRY(id, VERSION, CITIZENSHIP_CODE, CITIZENSHIP_NAME) VALUES (
1, 1, 643, 'Российская Федерация');

INSERT INTO ORGANIZATION(id, VERSION, SHORT_NAME, FULL_NAME, INN, KPP, ADDRESS, IS_ACTIVE) VALUES (
1, 1, 'Bell', 'Bell Integrator', '777777777777', '999999999', 'br. r', 1);

INSERT INTO OFFICE(id, VERSION, OFFICE_NAME, ADDRESS, IS_ACTIVE, ORGANIZATION_ID) VALUES (
1, 1, 'Bell office', 'qwerty', 1, 1);

INSERT INTO USR(id, VERSION, FIRST_NAME, USR_POSITION, IS_IDENTIFIED, OFFICE_ID) VALUES (
1, 1, 'Bell worker', 'Java Senior', 1, 1);

INSERT INTO DOCUMENT(id, VERSION, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE, CITIZENSHIP_ID, USR_ID) VALUES (
1, 1, 21, 'Паспорт Гражданина РФ', '445365', '1999-12-22', 1, 1);